-- ============================================
-- Phase 14: AI-generated entry titles
-- ============================================
-- Adds an optional `title` column to both personal entries and
-- community-shared copies. Titles are short (≤80 chars), descriptive
-- noun phrases generated by Claude Haiku from the entry text.
--
-- Nullable so existing rows stay valid until the backfill script
-- (`scripts/backfill-titles.ts`) populates them. New entries written
-- after this migration are expected to include a title; the partial
-- index makes the backfill query cheap.

alter table public.entries add column if not exists title text;
alter table public.community_entries add column if not exists title text;

create index if not exists entries_title_null_idx
  on public.entries (id) where title is null;

create index if not exists community_entries_title_null_idx
  on public.community_entries (id) where title is null;
